DROP DATABASE IF EXISTS Catalog;

CREATE DATABASE Catalog;

USE Catalog;

CREATE TABLE categories (
  id  INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(30) NOT NULL
);

CREATE TABLE items (
  Id INT(6) UNSIGNED AUTO_INCREMENT,
  Name VARCHAR(30) NOT NULL,
  Description VARCHAR(150),
  Category_id INT(6) UNSIGNED NOT NULL,
  Price FLOAT,
  Image VARCHAR(100),
  PRIMARY KEY (Id),
  FOREIGN KEY (Category_id) REFERENCES categories(id) ON DELETE CASCADE
);


DROP DATABASE IF EXISTS Test;

CREATE DATABASE Test;

USE Test;

CREATE TABLE categories (
  id  INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(30) NOT NULL
);

CREATE TABLE items (
  Id INT(6) UNSIGNED AUTO_INCREMENT,
  Name VARCHAR(30) NOT NULL,
  Description VARCHAR(150),
  Category_id INT(6) UNSIGNED NOT NULL,
  Price FLOAT,
  Image VARCHAR(100),
  PRIMARY KEY (Id),
  FOREIGN KEY (Category_id) REFERENCES categories(id) ON DELETE CASCADE
);